global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'web-app'
    static_configs:
      - targets: ['web:80']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
